spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hwmall_db?useSSL=false&serverTimezone=GMT&characterEncoding=utf8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.peng.hwmallservicedemo.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8080

logging:
  level:
    com.peng.hwmallservicedemo: debug
    org.apache.ibatis: debug
